### ISSUE TITLE
Please look rhino-licensing

### ISSUE THREAD

**Issue by VAllens** [EasyHelper/EasyLicense#1]
Please look rhino-licensing：
https://github.com/hibernating-rhinos/rhino-licensing
https://www.hibernatingrhinos.com/oss/rhino-licensing

**Comment by JayWang0** [comment]
Yes, I use some code of rhino-licensing, rhino-licensing is a good library, However It has more feature which I don't needed./,.

**Comment by VAllens** [comment]
yeah, 🙂
