### ISSUE TITLE
修改后 NET4.0 编译报错，

### ISSUE THREAD

**Issue by MrBenWang** [EasyHelper/EasyLicense#2]
[LicenseAttributes](https://github.com/EasyHelper/EasyLicense/blob/master/EasyLicense/EasyLicense.Lib/License/Validator/AbstractLicenseValidator.cs#L63) 属性是只读的，是不是遗漏代码

``` CSharp
protected AbstractLicenseValidator(string publicKey)
{
	LicenseAttributes = new Dictionary<string, string>();
	nextLeaseTimer = new Timer(LeaseLicenseAgain);
	this.publicKey = publicKey;
}

public virtual IDictionary<string, string> LicenseAttributes { get; }
```

**Comment by JayWang0** [comment]
Readonly property can be set in public ctor, anyway, You can use a private variable, and return the private variable in public property.

**Comment by MrBenWang** [comment]
I konw this. I want to tell you that the code may be not better. C# Compiler prompts, I can't set this property, in my development environment.
