### ISSUE TITLE
Incomplete Document

### ISSUE THREAD

**Issue by Manthan2611** [EasyHelper/EasyLicense#4]
Hi there,

Please provide a good document on how to get thing working. 
what will happen if lic is provided to one machine and a user copies whole application to another machine. will the application work in another machine ? 

Thanks & Regards,
Manthan Patel

**Comment by JayWang0** [comment]
Hi, Manthan,

I used to write an article to introduce this:
https://www.codeproject.com/Tips/1194451/Open-source-net-license-tool-EasyLicense

Currently, Yes, the application will work in another machine, if you don't want this ,you need to add your own logic while validing the license.

**Comment by Manthan2611** [comment]
Hi LoveJenny,

I have created a new Dictionary which contain Unique Hardware ID but now how can i validate it in Validator ? 

Can i used the below when i initialize the form? 

```
var dict = validator.LicenseAttributes;
	
                if (dict["hardware"] != getUniqueID("C"))
				{
					MessageBox.Show("invalid! machine");
				}
```

**Comment by JayWang0** [comment]
Yes,   You did a good job.
